"""Initial revision

Revision ID: 7bf4f8f39278
Revises: f300ddb8c34f
Create Date: 2024-10-11 19:48:19.403814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bf4f8f39278'
down_revision: Union[str, None] = 'f300ddb8c34f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'tickets', 'users', ['user_id'], ['telegram_id'])
    # ### end Alembic commands ###
